name: 'Setup vrc-get'
description: 'Setup vrc-get (https://github.com/anatawa12/vrc-get)'
inputs:
  version:
    description: 'version of vrc-get. by default, latest version will be used'
    default: latest
    required: false
  target:
    description: 'target triple to be downloaded for. By default, current platform will be used'
    required: false
  override:
    description: 'override existing vrc-get'
    default: 'true'
    required: false
  fix-official-curated-repository:
    description: |
      Use direct link for accessing official / curated repository.
      This would use experimental vrc-get feature.
      This is for recent workaround accessibility problem.
    default: false
runs:
  using: "composite"
  steps:
    - id: main
      run: bash "$GITHUB_ACTION_PATH/main.bash" "$VERSION" "$TARGET" "$OVERRIDE" "$FIX_OFFICIAL_CURATED_REPOSITORY"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        TARGET: ${{ inputs.target }}
        OVERRIDE: ${{ inputs.override }}
        FIX_OFFICIAL_CURATED_REPOSITORY: ${{ inputs.fix-official-curated-repository }}
branding:
  icon: 'award'
  color: 'green'
