name: 'Setup vrc-get'
description: 'Setup vrc-get (https://github.com/anatawa12/vrc-get)'
inputs:
  workspace:
    description: Path to your project. By default, GITHUB_WORKSPACE will be used.
    default: ${{ github.workspace }}
    required: false
  version:
    description: 'version of vrc-get. by default, latest version will be used'
    default: latest
    required: false
  target:
    description: 'target triple to be downloaded for. By default, current platform will be used'
    required: false
  repository:
    description: 'url to git repository'
    default: ${{ github.server_url }}/${{ github.repository }}.git
    required: false
  head:
    description: The head ref. By default, `github.head_ref` will be used.
    default: ${{ github.event.pull_request.head.sha }}
    required: false
  base:
    description: The base ref. By default, `github.base_ref` will be used.
    default: ${{ github.event.pull_request.base.sha }}
    required: false
runs:
  using: "composite"
  steps:
    - id: main
      run: bash "$GITHUB_ACTION_PATH/main.bash" "$VERSION" "$TARGET" "$WORKSPACE" "$REPOSITORY" "$HEAD" "$BASE"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        TARGET: ${{ inputs.target }}
        WORKSPACE: ${{ inputs.workspace }}
        REPOSITORY: ${{ inputs.repository }}
        HEAD: ${{ inputs.head }}
        BASE: ${{ inputs.base }}
branding:
  icon: 'award'
  color: 'green'
